### ISSUE TITLE
can't get homeduino responding

### ISSUE THREAD

**Issue by kregory** [pimatic/homeduino#20]
homeduino with uno don't respond to my ping while make monitor

It's compiled with pi

**Comment by sweetpi** [comment]
Try with the arduino ide.

**Comment by kregory** [comment]
same thing with the arduino ide
I just get "ready" and nothing happen when sending "PING hello" ctrl+enter

**Comment by kregory** [comment]
Using gedit and pasting text do the trick.
Maybe there is an issue with screen over ssh ...
