### ISSUE TITLE
Pir4 missing unit and is no longer working

### ISSUE THREAD

**Issue by rick00001** [pimatic/homeduino#22]
Hi,

After the last upgrade my doorbells aren't working. After the update Pir4 no longer has an unit. In the messages (debug) unit is still present.

Greatings Rick

**Comment by Icesory** [comment]
Can you show the debug output. We havent change anything on the pir4 protocol. But we have implemented a new config check.

**Comment by rick00001** [comment]
Hi Icesory,

Here is my debug information:
As  you can see it says that there isn't a property called "unit" 

In my screenshot the unit is show in the debug message of the doorbel.
![screenshot_2016-02-09-16-24-39](https://cloud.githubusercontent.com/assets/17128511/12921021/95e75238-cf4b-11e5-8af6-efc4bd986ae8.png)

10:11:28.328 [pimatic] info: Starting pimatic version 0.8.98
10:11:31.217 [pimatic] info: Loading plugin: "pimatic-cron" (0.8.6)
10:11:31.990 [pimatic] info: Loading plugin: "pimatic-mobile-frontend" (0.8.81)
10:11:33.525 [pimatic] info: Loading plugin: "pimatic-sysinfo" (0.8.13)
10:11:33.855 [pimatic] info: Loading plugin: "pimatic-wakeonlan" (0.2.1)
10:11:33.926 [pimatic] info: Loading plugin: "pimatic-shell-execute" (0.8.14)
10:11:33.978 [pimatic] info: Loading plugin: "pimatic-homeduino" (0.8.69)
10:11:35.542 [pimatic] info: Loading plugin: "pimatic-ping" (0.8.9)
10:11:35.628 [pimatic] info: Loading plugin: "pimatic-bh1750" (0.1.1)
10:11:35.670 [pimatic] info: Loading plugin: "pimatic-openweather" (0.8.18)
10:11:35.821 [pimatic] info: Loading plugin: "pimatic-smartmeter" (0.0.15)
10:11:35.861 [pimatic] info: Loading plugin: "pimatic-pushover" (0.8.5)
10:11:35.924 [pimatic] info: Loading plugin: "pimatic-sunrise" (0.8.2)
10:11:35.987 [pimatic-cron] info: the time is: Tue Feb 09 2016 10:11:35 GMT+0100 (CET)
10:11:36.378 [pimatic-sunrise] info: Your location is set to lat: 52.2631321, long: 6.1721879
10:11:36.543 [pimatic] info: New device "Status: CPU"...
10:11:36.584 [pimatic] info: New device "Status: overige"...
10:11:37.061 [pimatic] info: New device "Lux sensor"...
10:11:37.094 [pimatic] info: New device "Diskstation"...
10:11:37.131 [pimatic] info: New device "Commando's"...
10:11:37.169 [pimatic] info: New device "Google.nl"...
10:11:37.203 [pimatic] info: New device "Telefoon Rick"...
10:11:37.240 [pimatic] info: New device "Telefoon Lizet"...
10:11:37.263 [pimatic] info: New device "Tablet"...
10:11:37.288 [pimatic] info: New device "Diskstation"...
10:11:37.326 [pimatic] info: New device "Laptop"...
10:11:37.351 [pimatic] info: New device "Desktop"...
10:11:37.376 [pimatic] info: New device "MediaBox"...
10:11:37.445 [pimatic] info: New device "Weer"...
10:11:37.479 [pimatic] info: New device "Woonkamer klimaat"...
10:11:37.508 [pimatic] warn: Device configuration of light-schakel-waarde: Unknown config entry with name unit.
10:11:37.512 [pimatic] info: New device "Lampen inschakelen bij:"...
10:11:37.554 [pimatic] info: New device "Contact Shutdown"...
10:11:37.596 [pimatic] info: New device "Status: "...
10:11:37.638 [pimatic] info: New device "Mode: "...
10:11:37.702 [pimatic] info: New device "Status: "...
10:11:37.732 [pimatic] info: New device "Mode: "...
10:11:37.781 [pimatic] info: New device "Alle lampen"...
10:11:37.818 [pimatic] info: New device "Kleine lamp"...
10:11:37.863 [pimatic] info: New device "Grote lamp"...
10:11:37.906 [pimatic] info: New device "Kerstboom"...
10:11:37.942 [pimatic] info: New device "Alle lampen"...
10:11:37.983 [pimatic] info: New device "Ornament lamp"...
10:11:38.027 [pimatic] info: New device "Ornament pomp"...
10:11:38.076 [pimatic] info: New device "Tuin lamp"...
10:11:38.110 [pimatic] info: New device "Lamp Rick"...
10:11:38.152 [pimatic] info: New device "Lamp Lizet"...
10:11:38.189 [pimatic] info: New device "Schakelaar"...
10:11:38.237 [pimatic] error: Error loading device voordeur-bel: Protocol "pir4" has no property named "unit". Available properties are: "id" "presence" 
10:11:38.813 [pimatic] error: Error loading device poort-bel: Protocol "pir4" has no property named "unit". Available properties are: "id" "presence" 
10:11:38.867 [pimatic] info: New device "Schakelaar1"...
10:11:38.926 [pimatic] info: New device "Schakelaar2"...
10:11:38.971 [pimatic] info: New device "Schakelaar3"...
10:11:39.005 [pimatic] info: New device "Schakelaar4"...
10:11:39.048 [pimatic] info: New device "Schakelaar5"...
10:11:39.088 [pimatic] info: New device "Schakelaar7"...
10:11:39.124 [pimatic] info: New device "Schakelaar14"...
10:11:39.159 [pimatic] info: New device "Schakelaar15"... 
10:11:39.271 [pimatic] info: New device "Schakelaar10"...
10:11:59.602 [pimatic] error: Could not parse rule "if $voordeur-bel.presence increased then push title:"Voordeur bel!" message:"Er staat iemand bij de voordeur, ik zou maar gauw open doen als je thuis bent..." priority:1": Could not find an provider that decides next predicate of "$voordeur-bel.presence increased".
10:12:00.018 [pimatic] error: Could not parse rule "if $poort-bel.presence increased then push title:"Poort bel!" message:"Er staat iemand bij de poort, ik zou maar gauw open doen als je thuis bent..." priority:1": Could not find an provider that decides next predicate of "$poort-bel.presence increased".
10:12:00.271 [pimatic-ping] warn: Error on ip lookup of Desktop: Error: queryA ENOTFOUND
10:12:00.548 [pimatic-mobile-frontend] info: packing static assets
10:12:01.273 [pimatic-mobile-frontend] info: packing static assets finished
10:12:01.287 [pimatic-mobile-frontend] info: rendering html
10:12:08.402 [pimatic-mobile-frontend] info: rendering html finished
10:12:08.454 [pimatic] info: Listening for HTTP-request on port 8081...
10:12:08.610 [pimatic-homeduino] info: Connected to homeduino device.

**Comment by Icesory** [comment]
Thanks for the hint. The protocol pir4 is missing the unit field in the description. I will ad it und publish a fix.
