### ISSUE TITLE
pi does not automatically mount homeduino on /dev/ttyUSB0

### ISSUE THREAD

**Issue by tomvo** [pimatic/homeduino#26]
When I reboot my pi the serial interface is unavailable, I have to physcially remove and insert the USB cable to make my pi recognize the arduino/homeduino.
Is there a solution to this?

**Comment by mwittig** [comment]
Maybe the OS assigns another device id on reboot. Please check if you see any usb device after reboot (before removing and inserting the usb cable).

```
ls /dev/ttyUSB*
dmesg | grep usb
```

**Comment by gine78** [comment]
i have the same issue. 
if i shutdown the raspberry with the homeduino connectet via USB, the raspberry dit not find it.

i must just shutdown the raspberry, unplug the homeduino, restart the raspberry, stop Pimatic, plug in the homeduino, start pimatic.

This is my workaround.
HW: Raspberry Pi B+ and Raspberry Pi3 both the same issue.

**Comment by mwittig** [comment]
The following hint should solve the issue. Re-open otherwise

https://forum.pimatic.org/topic/42/tip-homeduino-usb
