### ISSUE TITLE
Always "timeout"

### ISSUE THREAD

**Issue by t1m02k16** [pimatic/homeduino#27]
after a certain time homeduino increases no longer works. I always get the message "timeout" no error messages in the log or elsewhere . I just need to restart the pimatic and it works again for a while

**Comment by mwittig** [comment]
See https://forum.pimatic.org/topic/1489/homeduino-timeout

**Comment by mwittig** [comment]
I am closing this ticket. Please follow up on the Forum thread. Thanks
