### ISSUE TITLE
Homeduino Contact - error in extentions - labels

### ISSUE THREAD

**Issue by skipper79** [pimatic/homeduino#5]
Renaming the labels of my contacts, using "xOnLabel" and "xOffLabel", gives an error.

As mentioned in device-config-schema.coffee it should be possible;

HomeduinoRFContactSensor: { 
  title: "HomeduinoRFContactSensor config options" 
  type: "object"   
  extensions: ["xConfirm", "xLink", "xOnLabel", "xOffLabel"]

**Comment by sweebee** [comment]
Labels dont work on contacts. I want it too, doe my doorbel. Waiting.../pressed instead of closed/opened.

**Comment by sweetpi** [comment]
Thanks for the info. These was the extensions only for switches, I corrected them to  xClosedLabel and xOpenedLabel. Please reopen the issue if the problem still exists after updating pimatic and pimatic-homeduino.

**Comment by sweebee** [comment]
Is there a way to change this closed to "Wachten..."?
![schermafbeelding 2015-01-18 om 22 34 09](https://cloud.githubusercontent.com/assets/10496485/5794152/37674656-9f62-11e4-9bcb-7c6988494f9f.png)

**Comment by sweetpi** [comment]
It should pick up the label here, too. Refresh (F5)?

**Comment by sweebee** [comment]
Working after clearing my cache.
