### ISSUE TITLE
pins assignment restriction?

### ISSUE THREAD

**Issue by sebastienvg** [pimatic/homeduino#6]
I am trying to reuse a ninjacrust (an arduino RF capp for the raspberryPI). The transceiver and receiver have their own pods on the board and you can't move them around unless you don't care to have them hanging. The modules use pins 3 and 5 and when I set those up in the pimatic config.json it refuses to start saying that pin must be 0 or 1, I then edited node_modules/pimatic-homeduino/homeduino.coffee and replaced "0, 1" with "0, 5" and now it starts.

What I am wondering is the reason to restrict the pin to 0 or 1 ? What issue am I running into if I try using different ports?

**Comment by cklam2** [comment]
In the Homeduino project the Arduino Nano is being used to connect to the RPI. When using this board then you can only use pin 0 and 1 as receiver pin. Same for sender pin which must be pin 2..13.

I remember a post where someone was trying to connect the receiver to a pin other than 0 and 1 and he couldn't get it working. Therefore sweetpi committed change [6a128c9](https://github.com/pimatic/pimatic-homeduino/commit/b0184de9a4e7eae8b1ca45ca822edf3d669abd31) where the restriction has been added.

If you're not using the Nano then shouldn't harm when using a different pin. As long as it works, right?

**Comment by punchlinegroup** [comment]
I appreciate the answer, thank you. Indeed I don't believe the arduino is a nano on this board because it seems to receive properly signal when I `` make monitor`` and then push buttons on the remote. Now I need to figure how to create RF devices to try sending.

**Comment by cklam2** [comment]
What do you mean with how to create RF devices? How to define them in config.json?
The homeduino readme doesn't give any clue. [This](http://pimatic.org/plugins/pimatic-homeduino/) page however gives a lot of examples. Which switch (switch1..switch6) to use is trial & error. Unless you have another RF sender that can control the device. 

Just enable debugging in the config file, use sender to send a signal and you'll see in pimatic-daemon.log whether pimatic recognizes the signal. If so then you'll also see what switch, which id, etc. to use.

**Comment by sweetpi** [comment]
Lets continue here: https://github.com/pimatic/pimatic/issues/496
