### ISSUE TITLE
Auriol temperature sensor type IAN 91838 not detected

### ISSUE THREAD

**Issue by Heizelmann** [pimatic/homeduino#8]
I have an Auriol weather station with a simple temperature sensor. My pimatic-homeduino logs  periodically similar things like this:
21:11:42.635 [pimatic-homeduino] debug: data: "RF receive 444 1992 3955 9330 0 0 0 0 010202010201010202010101010101010101010202020102020202010202010103"
21:11:42.672 [pimatic-homeduino] debug: received: [ 444, 1992, 3955, 9330 ] 010202010201010202010101010101010101010202020102020202010202010103
21:12:13.636 [pimatic-homeduino] debug: data: "RF receive 447 1991 3950 9329 0 0 0 0 010202010201010202010101010101010101010202020102020202010202010103"
21:12:13.673 [pimatic-homeduino] debug: received: [ 447, 1991, 3950, 9329 ] 010202010201010202010101010101010101010202020102020202010202010103
21:12:44.635 [pimatic-homeduino] debug: data: "RF receive 445 1993 3950 9338 0 0 0 0 010202010201010202010101010101010101010202020102020202010202010103"
21:12:44.673 [pimatic-homeduino] debug: received: [ 445, 1993, 3950, 9338 ] 010202010201010202010101010101010101010202020102020202010202010103
but it seems that there is no device detected.

What might be the problem? Isn't it supported. 
With Pilight it works well. The pilight config is as follows. Only temperature is valid, humidity is not correct.
"weather": {
			"protocol": [ "auriol" ],
			"id": [{
				"id": 1
			}],
			"temperature": 0.0,
			"humidity": 19.8,
			"battery": 1
		}

**Comment by sweetpi** [comment]
see https://github.com/pimatic/pimatic-homeduino/issues/25

**Comment by Heizelmann** [comment]
It works. :smile: Device is detected now and temperature value is correct. The humidy value I think can be removed, because it is not valid. As far as I know my Sensor have no humidity sensor.
